# используем язык java. Travis CI поддерживает другие языки тоже.
language: java

jdk: openjdk12

services:
  - postgresql

sudo: enabled

addons:
    postgresql: "10"

before_script:
  - psql -c "CREATE DATABASE Forum;" -U postgres
  - sudo -u postgres psql -c "ALTER ROLE postgres WITH password 'password'"

# Отправлять уведомление на почту youremail@smtp.ru (изменить на свою), если сборка упала
notifications:
  email:
    recipients:
      quaresma_08@mail.ru
    on_success: never # default: change
    on_failure: always # default: always
