language: java
jdk: openjdk12
sudo: false
install: true
script: mvn clean package -DskipTests=true
notifications:
  email:
    recipients: "-quaresma_08@mail.ru"
    on_success: never
    on_failure: always
services:
- postgresql
before_script:
- psql -c 'create database forum;' -U postgres
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - CODECOV_TOKEN="347e52bf-eeaa-427a-955b-12dae69e94b0"
deploy:
  provider: heroku
  api_key:
    secure: kHYpq+tDZVG0FSDE/PPZjoe7wc53bOGMiHX6LNRPAQ1WtnPu5CEXCYrNl0v0EUT1shRA98VdlhyBvUeBsRAHqCCoPupmrdDwB7P3vH0bOtc5vCjjF6Glh7aHBSZt1/0nglH1WLV0M4rQmqMW/E844fKBfWZUjfzxZr5VEppq8GspN92uCtjJ9l+u8msMkgZ+EIqnNfJM3sWS53xhH9uuJZ/Cz4SaeWd7pkE44MPGXfoFj8orZgBNAYaI4I2I39uehidwNgY6kPNjr5P3w9dcCF1yDkpe4Vw5C159ISiQMDjJClDQY3GPt0U7Xj8a/wyCkPiNGJvI7E2Kmouew4Bph2ZJltgUCE6LT2i4MUGlolJCYmv82LJQMsq/nFDK45RQ3uKhj9i/ioljrh6503N5Zp4U9vUOjSTK8ReP79Xk/KO+BlOh709lzMrc7MAGyRRIzVDwYxJDWm9Zrg4K3kRLk3YrAmxPaDLQRsCRItYIFJHrpKS1xVIjy/zENVCOkwWkq8PVv352i9zBHqoIK9RfyIaV+KgFK7ix9XGZX2lHZkxmP8cwRCKNQzLQ+E5DXZNUhiPGwVP8jAH/io/psSQrdvnYZq0EP8E0Yg+C3o9mUrtq9JfZ6nZ7ugvbsKE3bWKRx6E2cELq1VZJQCLQDBxbTedWzY1cwoB5Tl0/DpkVp5k=
  app: galaxy-forum
