language: java

jdk: openjdk12

services:
  - postgresql

before_install:
  - psql -c 'CREATE DATABASE Forum;' -U postgres

addons:
  postgresql: '11'
  apt:
      packages:
        - postgresql-11
        - postgresql-client-11

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      quaresma_08@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="347e52bf-eeaa-427a-955b-12dae69e94b0"


