language: java
jdk: openjdk12
sudo: false
install: true
script: mvn clean package -DskipTests=true
notifications:
  email:
    recipients: "-quaresma_08@mail.ru"
    on_success: never
    on_failure: always
services:
- postgresql
before_script:
- psql -c 'create database forum;' -U postgres
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - CODECOV_TOKEN="347e52bf-eeaa-427a-955b-12dae69e94b0"
deploy:
  provider: heroku
  api_key:
    secure: lthT/Jl2IKEFY904r0Wo0cCniQwJuHjHPofaiOzocc8CcvQTN6IxAT0gbJl5msaz5Md5cQHsUk7qdk5op10UTuhA8TS4xis6UZIHkF2z6H5WLCUJqzZKAPbC7f7KtqFPvEaxfwXGFyafcDvnqYDSSFiYYklTvzBaolXB9tGS9sYr2KisN+sPGBDpMG9TMfst9JwNwvt39nSn8s7H1XkAwOfz9NRi1jbBKZQ69a3dCmNsLSP9EFDj41vOi4FL/dTn5+pnHjjOLOiD4DNaptSxTWHG7ldV1G+THNwfU9IuGqiGMBqh/KKuOlZVXxoYphP0fbmAeOWPSp6bZop8I25BEFPnZStCS/pYab3wkXbZtrZ1gIwzRkiktO3UM5zXr92W/6pwXRPciaORRzft98QDZyLbCPA/kiitydDeYHWglOklWknxw6T7trmkffw7fAL+aZ5HVVgLSWhoRQECsB7wsKSKY3Hdxxmo53ASBemu55pIwDm5/xPR6j+chhuTmqAxkHii0g/Th2k4Oy67fLRBizYTbEq/m1OXkZMC0ZBYSzMahRgZ0VJTFrSqkQbOC56If+2ri3UTbnnGqNhP7HBTTAgEx1sIrKjP5aiaB4Dp8rWRkM2BGWJTs9SItYV/uJh79guQVx0/JOqvDrmL0kSAWA4ZVdZe/6KJvJiVGt4lzbo=
  app: galaxy-forum
