language: java

jdk: openjdk12

services:
  - postgresql

before_install:
- psql -c 'CREATE DATABASE Forum;' -U postgres

notifications:
  email:
    recipients:
      quaresma_08@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

