# используем язык java. Travis CI поддерживает другие языки тоже.
language: java

jdk: openjdk12

services:
  - postgresql

before_script:
  - psql -c 'create database Forum;' -U postgres

addons:
  postgresql: "10"

# Отправлять уведомление на почту youremail@smtp.ru (изменить на свою), если сборка упала
notifications:
  email:
    recipients:
      quaresma_08@mail.ru
    on_success: never # default: change
    on_failure: always # default: always
